name: Generate Report

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: ML_algorithm_selection_narges
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy matplotlib seaborn scikit-learn

    - name: Run the script
      run: |
        python algorithm_selection_narges.ipynb

    - name: Upload report
      uses: actions/upload-artifact@v2
      with:
        name: ML algorithm selection report.pdf
        path: ML algorithm selection report.pdfhttps://github.com/narhelmi/ML_algorithm_selection_narges/tree/main
